### ISSUE TITLE
Uncaught ReferenceError: ChartCalculator is not defined

### ISSUE THREAD

**Issue by stefanoa0** [CAYdenberg/Chart.js-ErrorBars#5]
Hey, I found that error on samples/box.html, anyone has the solution?

**Comment by CAYdenberg** [comment]
Well, bad news, I'm dropping this update because this API actually isn't much fun to work with. So for now, Box Plots only with the old version.

**Comment by stefanoa0** [comment]
Hi Casey,

I'm using the Chart/old from your repository and I get the box-plot. Well,
i'ts working fine, but I'm not seeing the outliers from box, and I see this:

// outliers
outlierShowLabels : true,
outlierLabelFormatter : function(s){return s;},
outlierLabelFontFamily : "'Arial'",
outlierLabelFontStyle : "normal",
outlierLabelFontSize : 12,        // pixels
outlierLabelFontColor : "#666",
outlierLabelPlacement : "right",  // left, top, bottom
outlierLabelMargin : 2,           // pixels. between label and dot
outlierDotStyle : 'disc',         // options: disc, circle
outlierDotFillColor : "#666",
outlierDotRadius : 2,             // pixels
outlierDotStrokeWidth : 2,        // pixels
outlierDotStrokeColor : "#666",

How I use this outliers like that: (the circles)



Thanks!!

(sorry for bad english)

2015-01-08 2:03 GMT-02:00 Casey Ydenberg <notifications@github.com>:

> Well, bad news, I'm dropping this update because this API actually isn't
> much fun to work with. So for now, Box Plots only with the old version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CAYdenberg/Chart.js-ErrorBars/issues/5#issuecomment-69133132>
> .
>



-- 
Stefano Azevedo da Silva
Graduado em Ciência da Computação
Cel: (73) 9196-8809

**Comment by stefanoa0** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "Queremos o fim das passagens de
primeira classe para os ministros do STF!" e queria saber se você pode
ajudar assinando também.

A nossa meta é conseguir 1.000.000 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/mXXsZQRMVJ

Obrigado!
STEFANO AZEVEDO
