### ISSUE TITLE
Is it up-to-date?

### ISSUE THREAD

**Issue by slacktracer** [CAYdenberg/Chart.js-ErrorBars#7]
Chart.js is awesome and error bars are a must to the project I'm working on. So thank you for this fork.

Is it up-to-date? I would like to use it but I need to be sure it's the latest chart.js plus error bars.

Let me know if you can. Thank you again.

**Comment by CAYdenberg** [comment]
I'm not sure what you mean by "up to date" exactly but I just merged in the latest 123 commits from nnnick/Chartjs (master) and retested all the samples. They work - but the samples aren't an exhaustive test suite so let me know if you experience any problems.

**Comment by slacktracer** [comment]
@CAYdenberg 

Yes! My main concern were those commits behind! =)

This fork is great. Thank you for your time, thank you very much.
