### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by ksallberg** [CAYdenberg/Chart.js-ErrorBars#9]
Possible to have the error bars as a plugin? I don't want to use this particular version of the chart JS file since it seems rather outdated compared to master?

**Comment by CAYdenberg** [comment]
Yeah - fair enough. The plugin API was added to Chart.js 2.0 right as I finished with this last time around, so this has been on my to-do list for a while.

**Comment by ksallberg** [comment]
Ok, no rush I guess, least for me. Found lib that provides all functionality I need. I'll close this.
